Repository prgrms-be-devcourse/NBE2_2_TEAM10, pull requests merged in 2024-10, with the labels that each got.

#50 pullrequest: JWT & Security 리팩토링
  build.gradle
  src/main/java/com/prgrms2/java/bitta/apply/service/ApplyServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/feed/controller/FeedController.java
  src/main/java/com/prgrms2/java/bitta/feed/service/FeedServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/jobpost/service/JobPostServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberController.java
  src/main/java/com/prgrms2/java/bitta/member/dto/MemberDTO.java
  src/main/java/com/prgrms2/java/bitta/member/dto/MemberProvider.java
  src/main/java/com/prgrms2/java/bitta/member/dto/SignInDTO.java
  src/main/java/com/prgrms2/java/bitta/member/dto/SignUpDTO.java
  src/main/java/com/prgrms2/java/bitta/member/entity/CustomMemberPrincipal.java
  src/main/java/com/prgrms2/java/bitta/member/entity/Member.java
  src/main/java/com/prgrms2/java/bitta/member/entity/Role.java
  src/main/java/com/prgrms2/java/bitta/member/repository/MemberRepository.java
  src/main/java/com/prgrms2/java/bitta/member/service/CustomUserDetailsService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/security/JwtAuthenticationFilter.java
  src/main/java/com/prgrms2/java/bitta/security/JwtToken.java
  src/main/java/com/prgrms2/java/bitta/security/JwtTokenProvider.java
  src/main/java/com/prgrms2/java/bitta/security/SecurityConfig.java
  src/main/java/com/prgrms2/java/bitta/security/SecurityUtil.java
  src/main/java/com/prgrms2/java/bitta/token/controller/TokenController.java
  src/main/java/com/prgrms2/java/bitta/token/filter/JWTCheckFilter.java
  src/main/java/com/prgrms2/java/bitta/token/util/JWTUtil.java
  src/test/java/com/prgrms2/java/bitta/controller/FeedControllerTests.java
  src/test/java/com/prgrms2/java/bitta/controller/JobPostControllerTests.java
  src/test/java/com/prgrms2/java/bitta/controller/MemberControllerTests.java
  src/test/java/com/prgrms2/java/bitta/controller/TokenControllerTests.java
  src/test/java/com/prgrms2/java/bitta/repository/MemberRepositoryTest.java
Labels: 🔧 refactor

#53 pullrequest: swagger refactoring
  build.gradle
  src/main/java/com/prgrms2/java/bitta/security/SecurityConfig.java
Labels: 🔧 refactor

#55 feat: 프로필 이미지 기능 추가
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberController.java
  src/main/java/com/prgrms2/java/bitta/member/entity/Member.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/member/service/ProfileImageService.java
  src/main/java/com/prgrms2/java/bitta/member/service/ProfileImageServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/images/default_avatar.png
Labels: ✨ feature

#57 feat: 프로필이미지 기타 설정 변경
  src/main/java/com/prgrms2/java/bitta/member/entity/Member.java
  src/main/java/com/prgrms2/java/bitta/security/SecurityConfig.java
Labels: ✨ feature

#62 feat: 프로필이미지와 회원관리 연동
  build.gradle
  src/main/java/com/prgrms2/java/bitta/global/config/WebConfig.java
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberController.java
  src/main/java/com/prgrms2/java/bitta/member/entity/Member.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/member/service/ProfileImageServiceImpl.java
  src/main/resources/application.properties
Labels: ✨ feature

#63 pullrequest : 삭제 시스템, 파일 제한 refactoring
  src/main/java/com/prgrms2/java/bitta/feed/controller/advice/FeedControllerAdvice.java
  src/main/java/com/prgrms2/java/bitta/feed/service/FeedServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/global/advice/GlovalExceptionHandler.java
  src/main/java/com/prgrms2/java/bitta/photo/service/PhotoServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/video/service/VideoServiceImpl.java
  src/main/resources/application.properties
Labels: 🔧 refactor

#72 bug: 회원관리 버그 수정
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberController.java
  src/main/java/com/prgrms2/java/bitta/member/dto/MemberDTO.java
  src/main/java/com/prgrms2/java/bitta/member/dto/SignUpDTO.java
  src/main/java/com/prgrms2/java/bitta/member/entity/Member.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/member/service/ProfileImageService.java
  src/main/java/com/prgrms2/java/bitta/member/service/ProfileImageServiceImpl.java
Labels: 🐞 bug

#73 pullrequest: AccessToken 재발급
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberController.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/security/JwtAuthenticationFilter.java
  src/main/java/com/prgrms2/java/bitta/security/JwtTokenProvider.java
  src/main/java/com/prgrms2/java/bitta/security/SecurityConfig.java
  src/main/java/com/prgrms2/java/bitta/security/dto/RefreshTokenRequestDTO.java
  src/main/java/com/prgrms2/java/bitta/security/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms2/java/bitta/security/exception/InvalidTokenException.java
  src/main/resources/.DS_Store
Labels: ✨ feature

#78 pullrequest: 토큰재발급 리팩토링 및 스웨거 수정
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberController.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/security/JwtTokenProvider.java
  src/main/java/com/prgrms2/java/bitta/security/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/uploads/.DS_Store
Labels: 🔧 refactor

#79 feat: 프로필이미지 썸네일 라이브러리 적용
  build.gradle
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberController.java
  src/main/java/com/prgrms2/java/bitta/member/dto/MemberDTO.java
  src/main/java/com/prgrms2/java/bitta/member/exception/NoChangeException.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberServiceImpl.java
  src/main/resources/test.images/test1-avatar.png
  src/main/resources/test.images/test2-avatar.png
  src/main/resources/test.images/test3_avatar.png
  src/main/resources/test.images/test4_avatar.png
Labels: ✨ feature

#88 refactor: 회원관리 리팩토링
  .gitignore
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberController.java
  src/main/java/com/prgrms2/java/bitta/member/controller/advice/TokenControllerAdvice.java
  src/main/java/com/prgrms2/java/bitta/member/dto/MemberDTO.java
  src/main/java/com/prgrms2/java/bitta/member/dto/SignInDTO.java
  src/main/java/com/prgrms2/java/bitta/member/dto/SignUpDTO.java
  src/main/java/com/prgrms2/java/bitta/member/entity/Member.java
  src/main/java/com/prgrms2/java/bitta/member/exception/MemberException.java
  src/main/java/com/prgrms2/java/bitta/member/repository/MemberRepository.java
  src/main/java/com/prgrms2/java/bitta/member/service/CustomUserDetailsService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/member/service/ProfileImageService.java
Labels: 🔧 refactor

#93 pullrequest: SecurityConfig 매핑 경로 수정
  src/main/java/com/prgrms2/java/bitta/security/SecurityConfig.java
Labels: 🔧 refactor

#101 pullrequest: uri 수정 및 추가
  src/main/java/com/prgrms2/java/bitta/global/config/SecurityConfig.java
Labels: 🔧 refactor

#102 feat: 회원가입, 로그인 front 설계
  src/main/java/com/prgrms2/java/bitta/global/controller/HomeController.java
  src/main/java/com/prgrms2/java/bitta/global/exception/AuthenticationException.java
  src/main/java/com/prgrms2/java/bitta/jobpost/controller/JobPostViewController.java
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberController.java
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberViewController.java
  src/main/resources/static/css/font.css
  src/main/resources/static/css/jobpost.css
  src/main/resources/static/css/member.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/style.css
  src/main/resources/static/images/complete.png
  src/main/resources/static/images/logo.png
  src/main/resources/templates/common/footer.html
  src/main/resources/templates/common/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/jobpost/jobpost.html
  src/main/resources/templates/member/join-complete.html
  src/main/resources/templates/member/join.html
  src/main/resources/templates/member/login.html
Labels: ✨ feature

#108 pullrequest: apply, jobPost 수정
  src/main/java/com/prgrms2/java/bitta/apply/controller/ApplyController.java
  src/main/java/com/prgrms2/java/bitta/apply/entity/Apply.java
  src/main/java/com/prgrms2/java/bitta/apply/repository/ApplyRepository.java
  src/main/java/com/prgrms2/java/bitta/apply/service/ApplyService.java
  src/main/java/com/prgrms2/java/bitta/apply/service/ApplyServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/global/config/SecurityConfig.java
  src/main/java/com/prgrms2/java/bitta/jobpost/controller/JobPostController.java
  src/main/java/com/prgrms2/java/bitta/jobpost/dto/JobPostDTO.java
  src/main/java/com/prgrms2/java/bitta/jobpost/entity/JobPost.java
  src/main/java/com/prgrms2/java/bitta/jobpost/repository/JobPostRepository.java
  src/main/java/com/prgrms2/java/bitta/jobpost/service/JobPostService.java
  src/main/java/com/prgrms2/java/bitta/jobpost/service/JobPostServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/media/service/MediaService.java
  src/main/java/com/prgrms2/java/bitta/media/service/MediaServiceImpl.java
  src/test/java/com/prgrms2/java/bitta/service/JobPostServiceTest.java
Labels: 🔧 refactor

#115 pullrequest: JWT일괄수정
  src/main/java/com/prgrms2/java/bitta/feed/controller/FeedController.java
  src/main/java/com/prgrms2/java/bitta/global/config/CorsMvcConfig.java
  src/main/java/com/prgrms2/java/bitta/global/config/SecurityConfig.java
  src/main/java/com/prgrms2/java/bitta/global/util/AuthenticationProvider.java
  src/main/java/com/prgrms2/java/bitta/jobpost/controller/JobPostViewController.java
  src/main/java/com/prgrms2/java/bitta/member/controller/JoinController.java
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberController.java
  src/main/java/com/prgrms2/java/bitta/member/dto/CustomUserDetails.java
  src/main/java/com/prgrms2/java/bitta/member/dto/JoinDTO.java
  src/main/java/com/prgrms2/java/bitta/member/dto/LoginDTO.java
  src/main/java/com/prgrms2/java/bitta/member/dto/MemberRequestDto.java
  src/main/java/com/prgrms2/java/bitta/member/entity/Member.java
  src/main/java/com/prgrms2/java/bitta/member/entity/Role.java
  src/main/java/com/prgrms2/java/bitta/member/repository/MemberRepository.java
  src/main/java/com/prgrms2/java/bitta/member/service/CustomUserDetailsService.java
  src/main/java/com/prgrms2/java/bitta/member/service/JoinService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberDetailsService.java
  src/main/java/com/prgrms2/java/bitta/token/controller/ReissueController.java
  src/main/java/com/prgrms2/java/bitta/token/controller/TokenController.java
  src/main/java/com/prgrms2/java/bitta/token/dto/TokenRequestDto.java
  src/main/java/com/prgrms2/java/bitta/token/dto/TokenResponseDto.java
  src/main/java/com/prgrms2/java/bitta/token/entity/RefreshEntity.java
  src/main/java/com/prgrms2/java/bitta/token/filter/CustomLogoutFilter.java
  src/main/java/com/prgrms2/java/bitta/token/filter/JWTFilter.java
  src/main/java/com/prgrms2/java/bitta/token/filter/LoginFilter.java
  src/main/java/com/prgrms2/java/bitta/token/filter/TokenAuthenticationFilter.java
  src/main/java/com/prgrms2/java/bitta/token/repository/RefreshRepository.java
  src/main/java/com/prgrms2/java/bitta/token/service/ReissueService.java
  src/main/java/com/prgrms2/java/bitta/token/service/ReissueServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/token/util/JWTUtil.java
  src/main/java/com/prgrms2/java/bitta/token/util/TokenProvider.java
Labels: 🔧 refactor

#116 pullrequest: Member 회원관리 로직 수정 및 병합
  src/main/java/com/prgrms2/java/bitta/global/config/SecurityConfig.java
  src/main/java/com/prgrms2/java/bitta/member/controller/JoinController.java
  src/main/java/com/prgrms2/java/bitta/member/controller/MemberController.java
  src/main/java/com/prgrms2/java/bitta/member/dto/JoinDTO.java
  src/main/java/com/prgrms2/java/bitta/member/dto/MemberRequestDto.java
  src/main/java/com/prgrms2/java/bitta/member/service/JoinService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberService.java
  src/main/java/com/prgrms2/java/bitta/member/service/MemberServiceImpl.java
  src/main/java/com/prgrms2/java/bitta/member/util/MemberMapper.java
  src/main/java/com/prgrms2/java/bitta/token/filter/LoginFilter.java
Labels: 🔧 refactor
